In [1]:
import numpy as np

In [4]:
l = [1,2,3,4,5,6]

In [6]:
a = np.array(l)
a

array([1, 2, 3, 4, 5, 6])

In [8]:
b = np.asarray(l)
b

array([1, 2, 3, 4, 5, 6])

In [15]:
c = np.asanyarray(l)
c

array([1, 2, 3, 4, 5, 6])

In [17]:
m = [[1,2,3,4,5,6],[1,2,3,4,5,6]]


In [22]:
mtx = np.matrix(m)
mtx

matrix([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]])

In [27]:
c = np.array(mtx)
c

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [29]:
type(c)

numpy.ndarray

In [32]:
type(mtx)

numpy.matrix

In [36]:
np.fromfunction(lambda i,j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [53]:
np.fromfunction(lambda i,j,k: (i == j) == k,(3,3,3))

array([[[False,  True, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [False,  True, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [False,  True, False]]])

In [50]:
ans = lambda i, j,k: i+j+k
print(ans(34,23,4))

61


In [3]:
# itrable function 
itrable = (i**3 for i in range(5))
# print(itrable)
# for i in itrable:
#     print(i)

In [77]:
np.fromiter(itrable,float)

array([ 0.,  1.,  8., 27., 64.])

In [6]:
np.fromstring("3 4 5", sep=' ')

array([3., 4., 5.])

In [14]:
np.zeros((3,4,2),float)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.arange(2,5,0.4)

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8])

In [23]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [30]:
np.logspace(34,2,23,base=2)

array([1.71798692e+10, 6.26841932e+09, 2.28715832e+09, 8.34515518e+08,
       3.04489699e+08, 1.11099165e+08, 4.05367551e+07, 1.47906469e+07,
       5.39666373e+06, 1.96908084e+06, 7.18458577e+05, 2.62144000e+05,
       9.56484882e+04, 3.48992664e+04, 1.27336963e+04, 4.64614409e+03,
       1.69523872e+03, 6.18541796e+02, 2.25687361e+02, 8.23465535e+01,
       3.00457891e+01, 1.09628079e+01, 4.00000000e+00])

In [25]:
np.empty((2,4))

array([[2. , 2.4, 2.8, 3.2],
       [3.6, 4. , 4.4, 4.8]])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.random.randn(3,5) # randn stands for standard deviation

array([[-1.05635005, -0.13273727,  0.55784765, -0.65230892,  0.21277876],
       [ 0.45798957, -0.92516047,  1.37997099, -0.9559618 , -0.46870018],
       [ 1.87657674, -0.93849115, -0.39241058, -0.67756424,  0.04901773]])

In [44]:
arr = np.random.rand(4,3) # rand generate randam data
arr

array([[0.63256177, 0.96308859, 0.29379033],
       [0.35370129, 0.76114053, 0.49335665],
       [0.19388562, 0.6886281 , 0.49427206],
       [0.07541159, 0.84887128, 0.91797934]])

In [45]:
arr.reshape(6,2)

array([[0.63256177, 0.96308859],
       [0.29379033, 0.35370129],
       [0.76114053, 0.49335665],
       [0.19388562, 0.6886281 ],
       [0.49427206, 0.07541159],
       [0.84887128, 0.91797934]])

In [47]:
arr.reshape(4,-232343) # given negative dimention it auto detacte right dimention 

array([[0.63256177, 0.96308859, 0.29379033],
       [0.35370129, 0.76114053, 0.49335665],
       [0.19388562, 0.6886281 , 0.49427206],
       [0.07541159, 0.84887128, 0.91797934]])

In [54]:
arr1 = np.random.randint(2,100,(5,5)) # randint(start, end, (dimentions))
arr1

array([[28, 95, 72, 94, 44],
       [17, 45, 15, 14, 28],
       [50, 35, 10, 44, 35],
       [15, 94, 89, 30, 36],
       [17, 12,  3, 99,  2]])

In [56]:
arr1[1:4,4]

array([28, 35, 36])

In [59]:
arr1[1:4,[2,4]]

array([[15, 28],
       [10, 35],
       [89, 36]])

In [61]:
arr2 = np.random.randint(10,50,(3,3))
arr2

array([[13, 17, 24],
       [14, 45, 25],
       [24, 28, 45]])

In [63]:
arr3 = np.random.randint(10,20,(3,3))
arr3

array([[13, 13, 10],
       [18, 17, 14],
       [18, 10, 18]])

In [64]:
arr2*arr3 # indexvise multiplecation

array([[169, 221, 240],
       [252, 765, 350],
       [432, 280, 810]])

In [66]:
arr2@arr3 # matrix multiplication

array([[ 907,  698,  800],
       [1442, 1197, 1220],
       [1626, 1238, 1442]])

In [69]:
arr2[arr2>2]

array([13, 17, 24, 14, 45, 25, 24, 28, 45])

In [73]:
arr2<20

array([[ True,  True, False],
       [ True, False, False],
       [False, False, False]])

In [79]:
arr4 = np.zeros((5,5))
arr4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
row = np.array([[1,2,3,4,5]])

In [87]:
arr4 + row # row wise broadcasting

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [90]:
column = row.T
column

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [95]:
arr = arr4+column
arr

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [97]:
arr+3

array([[4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8.]])

In [99]:
np.log10(arr)

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.30103   , 0.30103   , 0.30103   , 0.30103   , 0.30103   ],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [101]:
np.exp(arr)

array([[  2.71828183,   2.71828183,   2.71828183,   2.71828183,
          2.71828183],
       [  7.3890561 ,   7.3890561 ,   7.3890561 ,   7.3890561 ,
          7.3890561 ],
       [ 20.08553692,  20.08553692,  20.08553692,  20.08553692,
         20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003,
         54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ,
        148.4131591 ]])

In [102]:
np.sqrt(arr)

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798]])