In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,3))
arr

array([[2, 2, 5],
       [9, 7, 4],
       [4, 6, 8]])

In [4]:
arr1 = arr # arr can be used for arr1 here new copy is not genete but there refreance is generate

In [6]:
arr1

array([[2, 2, 5],
       [9, 7, 4],
       [4, 6, 8]])

In [8]:
arr2 = arr.view() # same here only refrence is generate and data is store in same location
arr2 

array([[2, 2, 5],
       [9, 7, 4],
       [4, 6, 8]])

In [9]:
arr3 = arr.copy()  # new copy is generate which is store in differnet location
arr3

array([[2, 2, 5],
       [9, 7, 4],
       [4, 6, 8]])

In [12]:
arr3.sort()
arr3

array([[2, 2, 5],
       [4, 7, 9],
       [4, 6, 8]])

In [18]:
arr1 = np.random.randint(1,50,10)
arr1

array([23, 16, 24, 19, 37, 25, 22,  6, 18, 35])

In [21]:
arr1.sort()
arr1

array([ 6, 16, 18, 19, 22, 23, 24, 25, 35, 37])

In [27]:
arr1.searchsorted(43) # give the location of sorted array where give element fil to maintain array sorted 

10

In [30]:
arr0 = np.eye(4)
arr0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
arr0.nonzero()

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [35]:
np.where(arr0 == 0) # give location of given condition true values

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]),
 array([1, 2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 2]))

In [37]:
np.count_nonzero(arr0)

4

In [41]:
 np.extract(arr1 > 2, arr1) 

array([ 6, 16, 18, 19, 22, 23, 24, 25, 35, 37])

In [43]:
arr1.byteswap()

array([ 432345564227567616, 1152921504606846976, 1297036692682702848,
       1369094286720630784, 1585267068834414592, 1657324662872342528,
       1729382256910270464, 1801439850948198400, 2522015791327477760,
       2666130979403333632])

In [44]:
import numpy.matlib as mn # matrix funtion subset of numpy arrays


In [46]:
mn.eye(3)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])